### ISSUE TITLE
Revise and unify the general webshop styling in figma

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1707]
## Context/goal: 
Make it look same way on all pages.

#### Products (list versus cards)
List has borders and shadows for each element, cards have no borders and shadows - we should add them
![Screenshot 2020-08-26 at 15 46 22](https://user-images.githubusercontent.com/33207036/91311453-66517c80-e7b3-11ea-9d5f-1a3d8602ace9.png)
![Screenshot 2020-08-26 at 15 46 26](https://user-images.githubusercontent.com/33207036/91311458-6782a980-e7b3-11ea-8a3b-0ab662a38695.png)
![Screenshot 2020-08-26 at 15 47 27](https://user-images.githubusercontent.com/33207036/91311504-75382f00-e7b3-11ea-8863-f14d1ef4a375.png)

#### Implement the new top menu (also without logo, quite generic):
https://www.figma.com/file/FMhzCEMbbTGiPjAmOvnTQn/Update-webshop-menu-bars?node-id=0%3A1

**Comment by danrminds** [comment]
@jamalv Can you please check out this page on the Webshop library? Can this be our initial general Webshop?
https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs/Webshop?node-id=898%3A7061

**Comment by jamalv** [comment]
@danrminds this is already great, but maybe let's update the components to replace dropshadows with outlines, it will be more consistent to the signupflows and look a bit less busy and more calm. Something like this:

https://www.figma.com/file/sCKcU3L1WuCUaznh9Ubcj3/Webshop---Play---Jamal?node-id=898%3A7061

![Screenshot 2020-09-22 at 19.39.14.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/6edb23f6-5747-45a6-96da-7870a3ba4288)

Instead of:

![Screenshot 2020-09-22 at 19.39.35.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/b8e1eec3-d8aa-4523-9ca9-57b44603c481)

And:

![Screenshot 2020-09-22 at 19.40.27.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/dc423ae4-1fd5-4ffe-92aa-a952153b736e)

Instead of:

![Screenshot 2020-09-22 at 19.42.58.png](https://images.zenhubusercontent.com/5bc6fc7b86f3a678d497cf05/c2dcef32-964b-4291-9402-a1c52196c196)

**Comment by jamalv** [comment]
Ah, I just noticed this task: https://github.com/teamforus/forus/issues/1708

Seems I got a bit too excited :P nevermind my comment then!

**Comment by sashooa** [comment]
https://www.figma.com/file/7lQX9ZRpJW3ZTCtEosAMzs/?node-id=898%3A7061

**Comment by jamalv** [comment]
Thx, for now this is good. Will not currently be worked on.
