### ISSUE TITLE
Unify webshop and signupflow styling (prototype)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1708]
## Context/goal: 
Create it as a new prototype - duplicate the webshop library - and update it to look similar to the signup flow
Things to pay attention to:

- Borders, no shadows
- Font styling, sizing, colouring
- Buttons, fields, dropdowns

Elements that might be missing and need to be done:
- Filters
- Breadcrumbs
- Pagination
- Tabs

**Comment by maxvisser** [comment]
@danrminds is this done?

**Comment by sashooa** [comment]
https://www.figma.com/file/8TlDC5dontgdtlO25CKsF3/?node-id=0%3A1

**Comment by jamalv** [comment]
@danrminds @sashooa I'm not the most interested high fidelity prototypes of every single page, but mostly in having modulair "building blocks" / a design system in place (atoms, molecules, organisms, templates) - this way it will be easier for us to build / adjust pages when we're making new things or improving existing ones. Now I often throw together a couple screenshots, making design review more work ;)

A good resource about this (5 minute read for the core message): https://atomicdesign.bradfrost.com/chapter-1/

**Comment by danrminds** [comment]
@jamalv I understand and I agree. That is what we are working now in #1902 for the dashboard. If you want we can switch to update the library of the Webshop accordingly (it will be faster than the dashboard anyway).

**Comment by jamalv** [comment]
Yea, let's start with the webshop for this. It has the highest impact for upcoming implementations. And it's better since it's already quite far in the unified style. (as we will later also unify the dashboards, following [max's branch](https://user-images.githubusercontent.com/30194799/101459864-1305d300-3939-11eb-8bcf-91e2673f50f5.png), less components means less maintainance and faster prototyping and development :))

The things that are important are the elements that will be styled differently every-time for the webshops and having good components for that (buttons, etc) - we can use one or two templates to build it up but as mentioned we don't need every single page that is currently in the webshop. Just the core "types" of pages (e.g. page with search and filters on the left and content on the right) if we have "atoms" and "organisms" for the different types of content, and they're set up right in Figma, it will be pretty easy to trow together a page prototype when that's needed.

The more we can re-use components, the better :) - so let's focus on the components that are used the most (buttons, forms, etc) and make sure they are in a design system with the separate states.
