### ISSUE TITLE
Change ALT attributes download buttons Me-app

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#2163]
De logo’s van de online winkels missen alt-attributen. 

De afbeeldingen die via img-elementen zonder alt-attributen zijn toegevoegd zorgen voor een ontoegankelijke ervaring omdat de bestandsnaam van de afbeelding wordt voorgelezen. 

Deze afbeeldingen zijn informatief en hebben daarom goede alternatieve teksten nodig. Geeft ze alt=’Google Play Store’ en alt=’Apple App Store’. De aria-labels op de link om de afbeelding heen, dient te worden verwijderd. Zie een vergelijkbare bevinding onder succescriterium 4.1.2.

**Comment by SjoerdHilhorst** [comment]
zijn dit niet twee issues, over aanbieder logo en over play en app-store logo?

**Comment by GerbenBosschieter** [comment]
I think something went wrong with the translation of this isue. I am not sure but I think that the issue should be about dowloading the me-app instead of shopkeers.

If thats the case, it's still not enough. Just adding title of the shop doesnt do the job. It's a redirect to the store where you can downalod the Me-app so the the text should describe this.

**Proposal**
- Android ALT text = "Download Me-app via de Play Store"
- Android ALT text = "Download Me-app via de App Store"

**Comment by GerbenBosschieter** [comment]
Edited the title. 

This issues doesn't describe WHERE the ALT text is missing. The download buttons are used on more than one place

**Comment by maxvisser** [comment]
@GerbenBosschieter we made a directive we can now use to add the download buttons anywhere; so it should be fixed everywhere

**Comment by GerbenBosschieter** [comment]
Checked and passed on Release/v0.24.0
