### ISSUE TITLE
Financial dashboard. Part 2 - Statistieken

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#2278]
## Context/goal: 

https://www.figma.com/file/VvtIJnhenSBskmAQSrzaGx/Financial-dashboard-improvements-SDOA?node-id=333%3A17343

![Screenshot 2021-04-22 at 12 33 11](https://user-images.githubusercontent.com/33207036/115700411-f063dc00-a366-11eb-84f0-8716c47163da.png)

In the statistics page we need to display a more generic overview, statistics of the financial part.

## Filtering and graph
Top bar is meant to do the filtering of the lower parts:
![Screenshot 2021-04-22 at 12 34 47](https://user-images.githubusercontent.com/33207036/115700607-23a66b00-a367-11eb-99e2-355da06f733c.png)

Filtering should happen by:
 - Fund
 - Provider
 - Category
 - Postcode
 - 
## Postcodes
For the postcode, we need to extract the postcode from the addresses of the providers (we can place it in a separate field). 
The postcode will look like: 9731 BK (we need to filter only by the digits. 
Can be done like a search or a dropdown with multiselect from the AVAILABLE postcodes (providers under this postcode).

Also, the Dag / Week / Maand / Kwartaal / Jaar will change the bottom timeframes. See example below:

https://user-images.githubusercontent.com/33207036/115701062-a9c2b180-a367-11eb-8fbe-8c4e6f8997d8.mov

As a priority for now would be Maand / Kwaartal / Jaar

Based on this the timeframe of the graph will differentiate. 

## Totals
Lower, we have some totals (for the selected timeframe):
![Screenshot 2021-04-22 at 12 39 53](https://user-images.githubusercontent.com/33207036/115701212-da0a5000-a367-11eb-89f7-23a3c74796e2.png)

Totaal uitgegeven = total amount spent at shops
Totaal transacties = number of transactions at shops

Hoogste aankoopbedrag = highest transaction
Bij aanbieder = provider where this highest transaction happened

Hoodste dagtotaal = highest daily total
Datum = when this happened

## Providers
And the last part is the providers. The list shows ALL PROVIDERS, but numbers change according to the filtering:
Totaal uitgegeven bij = total amount spent at this shop
Hoogste aankoopbedrag = highest transaction
Aantal transaction = number of transactions

![Screenshot 2021-04-22 at 12 45 07](https://user-images.githubusercontent.com/33207036/115701912-97954300-a368-11eb-939e-526acd5bf082.png)

**Comment by jamalv** [comment]
"Totaal uitgegeven = total amount spent at shops" - comment: https://www.figma.com/file/VvtIJnhenSBskmAQSrzaGx?node-id=323:7511#76092320

**Comment by linda-90** [comment]
@jamalv @danrminds - see comment in figma

**Comment by linda-90** [comment]
# Review

## Filters
<img width="554" alt="Schermafbeelding 2021-04-30 om 12 22 57" src="https://user-images.githubusercontent.com/36952230/116682656-ce91d700-a9ae-11eb-943a-361f1919cabe.png">

1. Filtering by year is active, the others (week, month, quarter) are not working yet
<img width="450" alt="Schermafbeelding 2021-04-30 om 12 36 12" src="https://user-images.githubusercontent.com/36952230/116684013-ab682700-a9b0-11eb-900c-a3ff9e8563bc.png">

2. Category filter is missing
3. Filter options: search bar is missing
4. Filter options: number of organizations is missing
<img width="381" alt="Schermafbeelding 2021-04-30 om 12 27 35" src="https://user-images.githubusercontent.com/36952230/116683129-75767300-a9af-11eb-8359-4589b40eb46a.png">
<img width="518" alt="Schermafbeelding 2021-04-30 om 12 33 50" src="https://user-images.githubusercontent.com/36952230/116683754-562c1580-a9b0-11eb-8925-65b91be2b27c.png">


## Chart
<img width="446" alt="Schermafbeelding 2021-04-30 om 12 37 41" src="https://user-images.githubusercontent.com/36952230/116684137-de121f80-a9b0-11eb-82a7-51d5d2514cb6.png">

5. Add euro sign to graph 'total spent'
<img width="531" alt="Schermafbeelding 2021-04-30 om 12 39 58" src="https://user-images.githubusercontent.com/36952230/116684381-2f221380-a9b1-11eb-80cb-9609c4e35120.png">

## Providers

6. The transactions (transactions buttons) per provider are missing (just like it works in the current dashboard) 
Add transaction button first. Add organization information later, so that the zip code will also be visible.
<img width="666" alt="Schermafbeelding 2021-04-30 om 12 45 54" src="https://user-images.githubusercontent.com/36952230/116685037-0a7a6b80-a9b2-11eb-9486-78de62c5067b.png">
