### ISSUE TITLE
Implementing transifex

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2337]
## Context/goal: 
Task is to identify if Transifex can speed up time spend on text review / implementing texts for errors etc.

## Task
- [ ] Support one of Transifex standard for translation files
- [ ] Import frontend i18n files from webshop / platform into transifex (would be nice to sync it with github)

**Comment by comradekingu** [comment]
Not that I have seen. Transifex is particularly bad at flagging errors, and worse yet at weeding out errors so that they even appear solved. Viewing more than half of another language is next to impossible.
What you want is good reviewers, and Weblate. Whether to do direct editing from a platform or rework each file by itself depends what state they are in. Translating stuff concurrently and at least continuously grants some benefits.

**Comment by maxvisser** [comment]
@comradekingu thanks for your insight. We at Forus are not planning to translate our application in alot of different languages (probably only English and Dutch). We were planning to use it for maintaining the language files and make it easier for non developers to change/fix/review texts on our application.

**Comment by comradekingu** [comment]
@maxvisser Happy to help if you get a libre license. You need every contributor up to this point to comply.
AGPLv3+ is my suggestion.
