### ISSUE TITLE
Popup: applying for fund [provider]

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#315]
**Is your feature request related to a problem? Please describe.**
The provider does not get any information after applying for a fund:
what is the waiting time, when does the fund start, how does he hear if he is accepted, where can he read why he isnt accepted

**Describe the solution you'd like**
Add a FAQ below the page of applying or add a popup after pressing 'apply' which tells the user he applied and he will get a mail with more information.

**Comment by maxvisser** [comment]
We need a pupup to display after the provider applied for the fund stating some information like:

- You request is recieved
- Please wait for the municipality to accept your request
- Average waiting time is x days
- etc.

@GerbenBosschieter I will need text we can show there, and after please reassign me, so I can give it to be designed to Alex.

**Comment by GerbenBosschieter** [comment]
Question. Do we know how long the municipalities will take the time to process the request? Otherwise I would just go for two business days until they tell us something else so we can change it.

And I wouldn't add the information about where they can find the reasoning for rejecting. Just add it to the e-mail itself.

text:

**Title**: Je aanvraag is ontvangen. 

De gemeente zal je verzoek behandelen, dit kan maximaal twee werkdagen duren. Zodra de gemeente je aanvraag heeft behandeld wordt er een e-mail toegestuurd. Daarnaast kan je de status ook volgen op het dashboard.

**Comment by maxvisser** [comment]
@linda-90 could you check this with nijmegen?

**Comment by maxvisser** [comment]
When ending the signupflow, we did not get a popup when applying. Popup seems not implemented.
