### ISSUE TITLE
Sign up flow: save progress.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#360]
**Is your feature request related to a problem? Please describe.**
When you fill in the signup flow. You now lose your progress when click it away. 
**Describe the solution you'd like**
I would like to save inputs and progress with cookies.

**Comment by danrminds** [comment]
hehe )

**Comment by ateamcms** [comment]
We can do it only when user fill form (step 2) with email and name and when user fill next form (step 3) - after user submit form on step 3 - if no validation errors in first form (step 2) - system creates identity and login user in frontend (user don't see it of course). So if we store data from forms after user loggined - next time when user return to sign-up page and we put data from cookie and he submit form (go to next step for example) will be error - because email will be taken already

**Comment by danrminds** [comment]
Also, we can save info for step 2 (individual info) - after pressing next. 
If you are filling in the information for organization (step 3) - and click next - you are already logged in - so no point where we can save anything.

 Only option here is to save the input while it is inserted (once in a few seconds) as a separate directive.
