### ISSUE TITLE
Display providers and offers dependent on the implementation and categories

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#373]
So, how I see it:

We have an implementation ID (same with the fund id)

We need:

- Connection of the sponsor id with the implementation id
- Filter and show only providers that are accepted by the sponsor of this implementation
- Filter and show only offers by providers that are accepted by the sponsor of this implementation
- Make a selection of categories ids to be shown for this implementation. Display only the ones. 

Step 1:
We batch it for the Zuidhorn only (hotfix for 23-11-2018)
Step 2:
For the 23-12-2018 - a good implementation of this.

**Comment by maxvisser** [comment]
- [ ] Don't show the shopkeepers of nijmegen on the map of zuidhorn (webshop)
  - only show shopkeepers approved for fund id 1
- [ ] Apply automatically to fund id 1 instead of the only fund 
- [ ] Don't show the products of nijmegen on the products page of zuidhorn (webshop)
  - meaning only show products from shopkeepers that are approved to fund id 1
-  [ ] Only show your own funds in sponsor dashboard. (remove funds as starting page, replace with my funds)

**Comment by maxvisser** [comment]
only show 'services' categories on webshop nijmegen https://github.com/teamforus/forus/issues/397
