### ISSUE TITLE
signupflow: I can´t take a step back.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#386]
During the shopkeeper sign-up process I need to be able to take a step back. My information should not be forgotten when doing so.

**Comment by danrminds** [comment]
Consider this as a very low priority. Due to the fact the flow of the signup flow is pretty complex (a lot of conditions of going back / forwards automatically makes it difficult to cache. 

The part of making you logging you in the Me App, and then back in the dashboard - can not be simulated, this can not be cached... this either has to be removed (if wanted to be cached), either close this issue

**Comment by maxvisser** [comment]
I think current version is ok but probably needs some refactoring in coming months. 

If i would change it, I would move the logging into Me app to the end of flow
