### ISSUE TITLE
Research JSON based databases for repositories.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#41]

**Comment by maxvisser** [comment]
@danrminds what is your planning with this research? Can you enrich this issue with your thoughts and comments.

**Comment by jamalv** [comment]
@jastam @maxvisser and I had a discussion about this yesterday and came to the conclusion that this will make it more feasible to "mirror" IPFS and a centralised solution (e.g. MongoDB). 

If we have a relational database instead of a json structure, the difference is much bigger and this will be much harder to do. Therefore we think this is definitely worth the effort.

**Comment by danrminds** [comment]
That is exactly why we decided to allocate 1-2 days to research this. 
Considering that the database had been separated (more or less) dependent on the repositories to be developed -> after discussing with Valentin I think would be possible to create an analog using JSON based database (as MongoDB).
I think will do the research during this weekend and maybe Monday. Tomorrow we should finish the Demo 2.0

**Comment by jastam** [comment]
The discussion where this issue/card came up was about storing data from our kindpakket schema in IPFS. 

IPFS is basically a file storage, so there is no concept for referencing data within data. For this reason IPFS behaves mostly like a document DB when looking at it from a database perspective. This makes the JSON format the natural format to store data on IPFS.

For storing/mirroring data from our current relational schema a translation will have to be made to the JSON format.
