### ISSUE TITLE
Provider requirements

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#5]
Share details
 - Chamber of commerce number
 - Provider display name
 - Operational area
 - Main categories

Add products / services to the platform
- See what products / services are being sponsored in your operational area
- Select the products / services that can be provided
- Select the price upper limit for the products / services
    - user will see the sponsored amount
        - if user sets higher amount sponsor will see that this provider needs
          higher funding
        - if user sets lower amount they will show up as a higher recommendation
           (ratings also get taken into a count here)
- Set availability for products related to fund (/ api link to inventory)
    - available (bool)
    - quantity (int)
- Add other products / services that can provided
  - when sponsorship ends, the selection from the previous step will go here

Provide product / service- Scan requester QR voucher code
- See the sponsored product / service + maximum value
- Select amount that product / service was delivered for
- Confirm and sign

**Comment by maxvisser** [comment]
can we make this issue more concrete? We talked in our feedback friday moment shortly about this between me, @danrminds and @jamalv. That we should create somekind of 'aanbiedingen' page. 

a bit like: http://aanbieding.marktplaats.nl/

**Comment by danrminds** [comment]
![03 shopkeeper dashboard](https://user-images.githubusercontent.com/33207036/38773021-df667e3c-4043-11e8-82c3-6661b0543128.png)

Provider dashboard flowchart. v0.0.1

**Comment by GerbenBosschieter** [comment]
I already talked with @maxvisser about the appropriate way to document this, I will comment them in this issue for now. Feedback is welcome :)

This list is work in progress.

**User stories Me-App**

Behind the user stories is an 'epic' and a kind of user.
Users = multiple roles (in this case the requester and provider).

* As a shopkeeper I want to be able to register my self on the Me-app so I can create a self sovereign company identity [ How to apply, Users ]
* As a shopkeeper I would like to have an transaction list so I can have an overview of all my transactions. [ How to pay, Users ]
* As a shopkeeper I would like to switch my tokens or cryptocurrencies to EURO or USD so I can add them to my  regular bookkeeping. [ How to pay, Users ]
* As a shopkeeper I would like to add multiple phones as a registered shopkeeper so different employers can use it. [ How to apply, shopkeeper ]
* As a shopkeeper I would like to have an web based overview so I can have a better view instead of a screen of the phone. [ How to search information, User]
* As a shopkeeper I want to be able to de refund and reference to an older transaction so it’s clear what refund belongs to what payment. [ How to pay, shopkeeper]
* As a shopkeeper I want to disable or enable certain phones if it got stolen / broken or lost so I am sure nobody has this information. [ How to secure, shopkeeper ]
* As a shopkeeper I would like to be validated as a shop by the chamber of commerce or the bank. [ How to apply, shopkeeper ]
* As a shopkeeper I would like to add different locations to the ‘records’ so it’s clear what location are connected to the me-app. [ how to search information, shopkeeper]
* As a shopkeeper I would like to have multiple account with different acces possibilities so the employees don’t see everything what belongs to the shop. [ how to secure, shopkeeper]
* As a shopkeeper I would like to have an option to create categories for certain products so I can choose instead of enter the category at a transfer. [ how to pay, shopkeeper]
* As a shopkeeper I would like to to have thew possibilities to give a discount instead of the changing the amount the product price so it’s clear what transaction had witch discount. [ how to pay, shopkeeper ]
* As a shopkeeper I would like to appoint multiple delegates or locations to restore identities. [ how to restore identity , shopkeeper ]


* As a shopkeeper I want to be able to have an overview of all the transactions that have been payed with kindapkket so I have an clear overview for my bookkeeping.  [ how to pay, shopkeeper]
* As a shopkeeper I would like to have a refund option so I can give the money back if there is something wrong with the product. [ how to pay, shopkeeper]
* As a shopkeeper I would like to have contact information so I can call someone if I have any questions. [how to search information, users ]
* As a shopkeeper I would like to have a step to step guideline on how the platform works. [ how to search information, users ]
* As a shopkeeper I want to be able to do a request to be a validated shopkeeper so s I can join the kindpakket program and sell my products / services to customers. [ How to apply, shopkeeper]
* As a shopkeeper I want to be able to add multiple locations so I can easily add new shops. [ how to apply, shopkeepers]
* As a shopkeeper I want to be able to change my contact information and openging times. [ how to search information, shopkeeper]

**User stories Me-App and Kinpakket**

* As a shopkeeper I want to be able to have an overview of all the transactions that have been payed with kindapkket so I have an clear overview for my bookkeeping.  [ how to pay, shopkeeper]
* As a shopkeeper I would like to have a refund option so I can give the money back if there is something wrong with the product. [ how to pay, shopkeeper]
* As a shopkeeper I would like to have contact information so I can call someone if I have any questions. [how to search information, users ]
* As a shopkeeper I would like to have a step to step guideline on how the platform works. [ how to search information, users ]
* As a shopkeeper I want to be able to do a request to be a validated shopkeeper so s I can join the kindpakket program and sell my products / services to customers. [ How to apply, shopkeeper]
* As a shopkeeper I want to be able to add multiple locations so I can easily add new shops. [ how to apply, shopkeepers]
* As a shopkeeper I want to be able to change my contact information and openging times. [ how to search information, shopkeeper]

**Comment by maxvisser** [comment]
@danrminds Gerben made these userstories, he used your big flow chart to do so. I personally think it would help to make an overview of user stories currently being worked on and which one's are finished.

**Comment by GerbenBosschieter** [comment]
@maxvisser I agree, and how about prioritising and valuation. Should this be added to the overview you're talking about

**Comment by GerbenBosschieter** [comment]
I will close this issue. The user stories are now embedded with the scrum sprint. Dan, Martijn and Yasha are now handling this.
