### ISSUE TITLE
Epic: Approving products

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#846]
## Description
A administrator of an implementation wants to approve products before they are shown in their implementation webshop.

**Comment by jamalv** [comment]
Clarification: this means that a sponsor will not approve shops. They will approve specific products / services instead. 

e.g. the "kruitvat" participates with kindpakket, but **only** with a scientific calculator.

**Comment by maxvisser** [comment]
estimation in based on just approving products instead of also disabling spending on budget level

**Comment by jamalv** [comment]
But isn’t that functionality kind of pointless? since people can still buy the product with their budget, even if the sponsor has disapproved it? I think without disallowing spending the budget, it will only confuse the sponsor; they say no, but the requester can still do it from the funds they’ve put up.

**Comment by maxvisser** [comment]
yes but disabling spending on budget level will mean alot for the workflow, just saying it will take more than 40h

issue arose again @jamalv with WK; they want to approve Primera on product level (instead of the whole shop)
