### ISSUE TITLE
Add menu items to top menu

### ISSUE THREAD

**Issue by maartenfv** [teamforus/forus#877]
![image](https://user-images.githubusercontent.com/30211022/58089414-f70ad700-7bc4-11e9-96e9-8b80e6c6119b.png)

We should add:

- Overzicht van aanbieders (Kaart) -> https://github.com/teamforus/forus/issues/1199
- Hoe het werkt
- Veelgestelde vragen
- Contact (link to footer or make pop-up or separate page?)

**Comment by maxvisser** [comment]
items you list are table of content items. Aanbieding is a page. Putting anchors in the menu also may cause some problems on mobile:
![image](https://user-images.githubusercontent.com/10818702/68932291-9682de00-0792-11ea-9699-34ecc0980f04.png)

**Comment by GerbenBosschieter** [comment]
My opinion:
- The discussion about this issue is already leading to a big iteration (new pages, not hiding the map behind the button etc etc) All these user flows will be refined in the redesign. So adding it to the current webshop is maybe not the way to go
- I like the proposal to add a menu item for the google maps card, because I got support questions about it.

**Comment by jamalv** [comment]
we have added aanbieders; currently having discussions about adding the other items, closing this issue in favour of https://github.com/teamforus/forus/issues/1360
