### ISSUE TITLE
Delete validators

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#89]
- [ ] Set up start date when assigning validator
- [ ] When deleting validator - change start date and set end date of trusted validations by that identity
- [ ] Retroactively delete all validations (in case of fraud for example)

**Comment by maxvisser** [comment]
I think we should never delete validations (only if the user askes for it), I would recommend to implement a soft delete by adding a new validation on the same record type.

**Comment by maxvisser** [comment]
As there are no external validators in the system before 1 jan, this feature can be lower on the backlog.

**Comment by danrminds** [comment]
The hard-delete (retroactively) - might be required for the system in case of suspecting or founding of evidence of fraud from a certain validator. 

Agree that this can be kept out before 1 jan

**Comment by maxvisser** [comment]
I think for investigation sake you would just want the validations to be disabled/not valid anymore instead of deleted.

**Comment by jamalv** [comment]
Agree with max here that it should indeed be a soft-delete. This one is a bit complex since it already goes to having some sort of “registry” for validators. This also enables organisations of validators.

By the way; it could make a lot of sense to store this registry in a publicly available smart contract.

For example:

## Westerkwartier registry:
validator | start-date | end-date
---|---|---
0xjlkj23l... | 2018-02-03 | -
0xsdlkf... | 2018-01-03 | 2018-03-06
0xsdlkf... | 2018-01-03 | -

It is then easy to check in the list if the record was validated by an identity that

**Comment by maxvisser** [comment]
I retract a bit of my statement. As a citizen you should be able to ask the validator for a hard delete (right to be forgotten). Should investigate this issue a bit more. Soft delete would make alot of sense if the system was already more technical decentralized but with centralized hosting of data Forus has to comply with avg ;)

**Comment by maxvisser** [comment]
@danrminds what do you want to do with this issue? I think close it and make seperate research issues as it is open since august.
