### ISSUE TITLE
add rog +1 gemeente webshop as screenshot on homepage

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#939]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/60246485-0e716a00-98bf-11e9-859c-79ff31570e2b.png)

https://app.zeplin.io/project/5bdc3c4e70ca1e723d0e6b16/screen/5d0ce531fba28c5a12becb4a

**Comment by GerbenBosschieter** [comment]
@jknnr 
- The title is currently  right above the screenshot, so can't remove more spacing. What do you exactly mean ? And on what screen resolution are you watching it, its differ per screen size so I know where to change it.
- If you want me to use the new screenshot, could you ask lena to upload it on zeplin ? And it would be nice if we didn't have the russian text in it.
- About the bold text, does it only need to change below Kindpakket title ? Because now it's aligned with the rest of the page and someone else changed the way the text looks and he was convinced it was the same as the design. So I would rather not overwrite it if not everybody aggrees.

@maxvisser the screenshot if the +1 thing is not good enough in my opinion.
The text is talking about zuidhorn and the rest of it is +1, thats weird.
Te text on the product is some gibberish and there is an example of an hover effect thats also little bit weird to display.
